name: 'JMeter Performance Test'
description: 'Runs performance tests using Apache JMeter'
runs:
    using: "composite"
    steps:
      - name: Set up Docker
        shell: bash
        run: |
          docker --version

      - name: Start Python App Container
        shell: bash
        run: |
          docker run -d --name python-app -p 8000:8000 myapp:latest
          sleep 5 # Wait for the app to start

      - name: Install Apache JMeter
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          mv apache-jmeter-5.5 jmeter
          echo "$(pwd)/jmeter/bin" >> $GITHUB_PATH

      - name: Verify JMeter Installation
        shell: bash
        run: |
          jmeter -v

      - name: Run JMeter Performance Test
        shell: bash
        run: |
          jmeter -n -t .github/actions/performance-test/jmeter-test.jmx -l results.jtl -e -o report

      - name: Check JMeter Test Results
        shell: bash
        run: |
          if grep -q '<failure>true</failure>' results.jtl; then
            echo "JMeter test failed! Check the report."
            exit 1
          else
            echo "JMeter test passed successfully!"
          fi

      - name: Stop and Remove Python App Container
        shell: bash
        run: |
          docker stop python-app
          docker rm python-app
