name: 'JMeter Performance Test'
description: 'Runs performance tests using Apache JMeter'
run: |
      docker run -d --name python-app -p 8000:8000 rsanchezcol/myapp:latest
      sleep 5 # Wait for the app to start
      
      # Install Apache JMeter
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jre
      wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
      tar -xvzf apache-jmeter-5.5.tgz
      mv apache-jmeter-5.5 jmeter
      echo "$(pwd)/jmeter/bin" >> $GITHUB_PATH

      # Verify JMeter Installation
      jmeter -v

      # Run JMeter Performance Test
      jmeter -n -t .github/actions/performance-test/jmeter-test.jmx -l results.jtl -e -o report

      # Check JMeter Test Results
      if grep -q '<failure>true</failure>' results.jtl; then
        echo "JMeter test failed! Check the report."
        exit 1
      else
        echo "JMeter test passed successfully!"
      fi

      # Stop and Remove Python App Container
      docker stop python-app
      docker rm python-app
