name: CI/CD Pipeline with Performance Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest mydockerhubuser/myapp:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push mydockerhubuser/myapp:${{ github.sha }}

  security-scan:
    name: Security Scan with Trivy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get install -y trivy

      - name: Scan Docker Image
        run: |
          trivy image mydockerhubuser/myapp:${{ github.sha }}

  performance-test:
    name: Run Performance Tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Performance Tests
        uses: ./.github/actions/performance-test
